version: 2

jobs:
  build:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run: docker-compose up -d
      - run: docker-compose exec php-fpm composer install -n --prefer-dist
      - run: docker-compose exec php-fpm php ./bin/phpunit
